#!/usr/bin/env bash
# 1-install_nginx_web_server

# Install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Insert 'Hello World' to index.html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

# Restart nginx
sudo service nginx restart
