#!/usr/bin/env bash
# Creates file "/var/run/myscript.pid" with PID
# Displays "To infinity and beyond" indefinitely
# Dislays "I hate the kill command" when receiving SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes file "/var/run/myscript.pid" & terminates itself when receiving a SIGQUIT/SIGTERM signal

trap "sudo rm -f /var/run/myscript.pid; exit" SIGQUIT
trap "echo I hate the kill command; sudo rm -f /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!; exit" SIGINT
touch /var/run/myscript.pid
while true
do
   echo "To infinity and beyond"
   sleep 2
done
