#!/usr/bin/env bash
# Manages "manage_my_process"
# Requirement :
# Passing "start"->Starts "manages_my_process" -> creates file containing PID in "/var/run/my_process.pid -> displays "manage_my_process"
# Passing "stop" ->Stops "manage_my_process -> delets file "/var/run/my_process.pid" -> displays "manage_my_process stopped"
# Passing "restart" ->Stops "manage_my_process" -> deletes file "/var/run/my_process.pid" -> starts manage_my_process -> creates file with PID
# in "/var/run/my_process.pid" -> Displays "manage_my_process restarted"

argv1=$1
tmpfile="/var/run/my_process.pid"

startLoop_n_createFile()
{
   ./manage_my_process &
   echo "$!" > "$tmpfile"
}
killLoop_n_rmFile()
{
   #kill "${cat "$tmpfile"}"
   sudo pkill 0f "./manage_my_process"
   rm "$tmpfile"
}
case "$argv1" in
   start) echo "manage_my_process started"
       startLoop_n_createFile
       ;;
   stop) echo "manage_my_process stopped"
       killLoop_n_rmFile
       ;;
   restart) echo "manage_my_process restarted"
       killLoop_n_rmFile
       startLoop_n_createFile
       ;;
   *) echo "Usage: manage_my_process {start|stop|restart}"
       ;;
esac
