#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# In-betwen each iteration of the loop, add sleep 2, accepts keyboard kill interrupt

while true
do
   echo "To infinity and beyond"
   sleep 2
done
