#!/usr/bin/env bash
# Indefinitely writes "I am alive!" to the file "/tmp/my_process"
# In between every "I am alive!" message, the program pauses for 2secs

touch /tmp/my_process
while true
do
   echo "I am alive!"
   sleep 2
done
