#!/usr/bin/env bash
# Displays from 1 to 100, Requirements:
# Displays FizzBuzz when num is multiple of 3 and 5
# Displays Fizz when num is multiple of 3
# Displays Buzz when num is multiple of 5
# Otherswise, displays the num in a list format

for i in {1..100}
do
   if [ $(( i%15 )) -eq 0 ]
   then
       echo "FizzBuzz"
   elif [ $(( i%5 )) -eq 0 ]
   then
       echo "Buzz"
   elif [ $(( i%3 )) -eq 0 ]
   then
       echo "Fizz"
   else
       echo "$i"
   fi
done
