#!/usr/bin/env bash
# Displays the visitor IP along the HTTP status code from "apache-access.log"
# Format: OCCURENCE_NUMBER IP HTTP_CODE in list format, order from the greatest to lowest num

file="apache-access.log"
awk '{print $1, $9}' $file | sort | uniq -c | sort -nr
