#!/usr/bin/env bash
# This displays "Best School" 10 times, but 9th displays "Hi"
counter=1
while [ $counter -le 10 ]
do
  echo "Best School"
  if [ $counter -eq 9 ]
  then
     echo "Hi"
  fi
  ((counter++))
done

