#!/usr/bin/env bash
# This displays num 1 to 20 and
# displays 4 then "bad luck from China"
# displays 9 then "bad luck from Japan"
# displays 17 then "bad luck from Italy"
counter=1
while [ $counter -le 20 ]
do
   echo $counter
   case $counter in
      4)
         echo "bad luck from China"
         ;;
      9)
         echo "bad luck from Japan"
         ;;
      17)
         echo "bad luck from Italy"
         ;;
   esac
   ((counter++))
done
