#!/usr/bin/env bash
# This displays the time from 12hrs & 59min
# displays hours from 0 to 12
# displays mins from 1 to 59
counter=0
while [ $counter -le 12 ]
do
    echo "Hour: $counter"
    min=1
    while [ $min -lt 60 ]
    do
       echo "$min"
       ((min++))
    done
    ((counter++))
done
